/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import javax.swing.table.DefaultTableModel;
import dbOperation.*;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Ravi Kandel
 */
public class ViewAllStudent extends javax.swing.JFrame {

    ArrayList list;
    /** Creates new form ViewAllStudent */
    public ViewAllStudent() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel.setColumnIdentifiers(colName);
        tblViewData = new javax.swing.JTable();

        tblViewData.setModel(tableModel);

        dbQueries dbQ = new dbQueries();
        ResultSet rs=dbQ.viewStudentInformation();

        String id,fname,lname,address,gender,phone,email,dob;

        try{
            while(rs.next()){
                id=rs.getString("id");
                fname=rs.getString("first_name");
                lname=rs.getString("last_name");
                address=rs.getString("address");
                gender=rs.getString("gender");
                phone=rs.getString("phone");
                email=rs.getString("email");
                dob=rs.getDate("dob").toString();

                tableModel.addRow(new Object[]{id,fname,lname,address,gender,phone,email,dob});

            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Something went Wrong!: " + ex.toString());
        }
        /*
        tblViewData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblViewData.setName("table"); // NOI18N
        tblViewData.setRowHeight(20);
        */
        tblViewData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewData);
        if (tblViewData.getColumnModel().getColumnCount() > 0) {
            tblViewData.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblViewData.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblViewDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewDataMouseClicked

        javax.swing.JTable table = (javax.swing.JTable) evt.getSource();
        Point p = evt.getPoint();
        int row = table.rowAtPoint(p);
                
        if (evt.getClickCount() == 2) {
                 ArrayList myList = new ArrayList();
                    myList.add(tableModel.getValueAt(row, 1).toString()); //fname
                    myList.add(tableModel.getValueAt(row, 2).toString()); //lname
                    myList.add(tableModel.getValueAt(row, 3).toString()); //address
                    myList.add(tableModel.getValueAt(row, 4).toString()); //phone
                    myList.add(tableModel.getValueAt(row, 5).toString()); //email
                    myList.add(tableModel.getValueAt(row, 6).toString()); //dob
                    myList.add(tableModel.getValueAt(row, 7).toString()); //gender
                    myList.add(tableModel.getValueAt(row, 0).toString()); //Adding id at last

                    UpdateStudent std = new UpdateStudent();
                    std.getData(myList);
                    
                    this.setVisible(false);
                    this.dispose();
                    
                    std.setVisible(true);
              }
    }//GEN-LAST:event_tblViewDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewData;
    // End of variables declaration//GEN-END:variables
String [] colName={"ID","FIRST NAME","LAST NAME", "ADDRESS", "GENDER","PHONE","EMAIL","DATE OF BIRTH"};
    DefaultTableModel tableModel = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
}
